version: "2"

services:
    ola:
        build: .
        image: ultracombos/ola
        volumes:
            - c:/docker/ola/config:/root/.ola
        ports:
            - "9090:9090"
        network_mode: host
        environment:
            PORT: 9090
        command: ./start.sh

